project:
    type: website

format:
    html:
        theme: [cosmo, _theme/atkinson.scss]
        css: _theme/styles.css
        include-before-body:
            file: _theme/accessibility.html
        grid:
          margin-width: 350px

website:
    title: "Display settings toolbar for Quarto"
    margin-header: _theme/_accessibility_sidebar.qmd
